# CHAPTER 6 Data Loading, Storage, and File Formats

Este capituilo se enfoca en mostrar el funcionamiento de pandas y python puro en el I/O de archivos, leer data de motores sql, de archivos en formato binario.

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Table 6-1. Text and binary data loading functions in pandas

| Function | Description |
| :--- | :--- |
| `read_csv` | Cargar datos delimitados desde un archivo, URL u objeto tipo archivo; utiliza la coma como delimitador por defecto |
| `read_fwf` | Leer datos en formato de columnas de ancho fijo (es decir, sin delimitadores) |
| `read_clipboard` | Variación de `read_csv` que lee datos desde el portapapeles; útil para convertir tablas de páginas web |
| `read_excel` | Leer datos tabulares desde un archivo Excel XLS o XLSX |
| `read_hdf` | Leer archivos HDF5 escritos por pandas |
| `read_html` | Leer todas las tablas encontradas en el documento HTML dado |
| `read_json` | Leer datos desde una representación de cadena JSON (JavaScript Object Notation), archivo, URL u objeto tipo archivo |
| `read_feather` | Leer el formato de archivo binario Feather |
| `read_orc` | Leer el formato de archivo binario Apache ORC |
| `read_parquet` | Leer el formato de archivo binario Apache Parquet |
| `read_pickle` | Leer un objeto almacenado por pandas usando el formato pickle de Python |
| `read_sas` | Leer un conjunto de datos SAS almacenado en uno de los formatos de almacenamiento personalizados del sistema SAS |
| `read_spss` | Leer un archivo de datos creado por SPSS |
| `read_sql` | Leer los resultados de una consulta SQL (usando SQLAlchemy) |
| `read_sql_table` | Leer una tabla SQL completa (usando SQLAlchemy); equivalente a usar una consulta que selecciona todo en esa tabla usando `read_sql` |
| `read_stata` | Leer un conjunto de datos desde el formato de archivo Stata |
| `read_xml` | Leer una tabla de datos desde un archivo XML |

In [3]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
pd.options.display.max_colwidth = 75
pd.options.display.max_columns = 20
np.set_printoptions(precision=4, suppress=True)

In [6]:
!type "examples/ex1.csv"

The system cannot find the file specified.

In [7]:
df = pd.read_csv("examples/ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
!type examples/ex2.csv

The syntax of the command is incorrect.

In [10]:
pd.read_csv("examples/ex2.csv", header=None)
pd.read_csv("examples/ex2.csv", names=["a", "b", "c", "d", "message"])

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [11]:
# You can either indicate you want the column at index 4 or named "message" using the index_col argument:
names = ["a", "b", "c", "d", "message"]
pd.read_csv("examples/ex2.csv", names=names, index_col="message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [12]:
!type examples/csv_mindex.csv
parsed = pd.read_csv("examples/csv_mindex.csv",
                     index_col=["key1", "key2"])
parsed

The syntax of the command is incorrect.

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [13]:
!type examples/ex3.txt

The syntax of the command is incorrect.

In [14]:
# Cuando las variables estan separadas por espacios
result = pd.read_csv("examples/ex3.txt", sep="\s+")
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [15]:
!type examples/ex4.csv
# For example, you can skip the first, third, and fourth rows of a file with skiprows
pd.read_csv("examples/ex4.csv", skiprows=[0, 2, 3])

The syntax of the command is incorrect.

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [16]:
!type examples/ex5.csv
#  By default, pandas uses a set of commonly occurring sentinels for missing Data, such as NA and NULL
result = pd.read_csv("examples/ex5.csv")
result

The syntax of the command is incorrect.

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [17]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [18]:
result = pd.read_csv("examples/ex5.csv", na_values=["NULL"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [19]:
result2 = pd.read_csv("examples/ex5.csv", keep_default_na=False)
result2
result2.isna()
result3 = pd.read_csv("examples/ex5.csv", keep_default_na=False,
                      na_values=["NA"])
result3
result3.isna()

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [20]:
sentinels = {"message": ["foo", "NA"], "something": ["two"]}
pd.read_csv("examples/ex5.csv", na_values=sentinels,
            keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

### Table 6-2. Some pandas.read_csv function arguments

| Argument | Description |
| :--- | :--- |
| `path` | Cadena que indica la ubicación en el sistema de archivos, URL u objeto tipo archivo. |
| `sep` or `delimiter` | Secuencia de caracteres o expresión regular a utilizar para separar los campos en cada fila. |
| `header` | Número de fila a utilizar como nombres de columnas; por defecto es 0 (primera fila), pero debería ser `None` si no hay fila de encabezado. |
| `index_col` | Números o nombres de columnas a utilizar como índice de filas en el resultado; puede ser un solo nombre/número o una lista de ellos para un índice jerárquico. |
| `names` | Lista de nombres de columnas para el resultado. |
| `skiprows` | Número de filas al principio del archivo que se van a ignorar o lista de números de filas (comenzando desde 0) que se van a omitir. |
| `na_values` | Secuencia de valores a reemplazar con NA. Se añaden a la lista por defecto a menos que se pase `keep_default_na=False`. |
| `keep_default_na` | Indica si se debe utilizar la lista de valores NA por defecto o no (`True` por defecto). |
| `comment` | Carácter(es) para separar los comentarios al final de las líneas. |
| `parse_dates` | Intenta convertir los datos a `datetime`; `False` por defecto. Si es `True`, intentará convertir todas las columnas. De lo contrario, se puede especificar una lista de números o nombres de columnas para analizar. Si el elemento de la lista es una tupla o lista, combinará múltiples columnas y las convertirá a fecha (por ejemplo, si la fecha/hora está dividida en dos columnas). |
| `keep_date_col` | Si se combinan columnas para analizar la fecha, conservar las columnas combinadas; `False` por defecto. |
| `converters` | Diccionario que contiene el número o nombre de la columna mapeado a funciones (por ejemplo, `{"foo": f}` aplicaría la función `f` a todos los valores de la columna "foo"). |
| `dayfirst` | Al analizar fechas potencialmente ambiguas, tratarlas como formato internacional (por ejemplo, 7/6/2012 -> 7 de junio de 2012); `False` por defecto. |
| `date_parser` | Función a utilizar para analizar las fechas. |
| `nrows` | Número de filas a leer desde el principio del archivo (sin contar el encabezado). |
| `iterator` | Devuelve un objeto `TextFileReader` para leer el archivo poco a poco. Este objeto también se puede utilizar con la sentencia `with`. |
| `chunksize` | Para la iteración, tamaño de los fragmentos (chunks) del archivo. |
| `skip_footer` | Número de líneas a ignorar al final del archivo. |
| `verbose` | Imprime diversa información del análisis, como el tiempo transcurrido en cada etapa de la conversión del archivo y la información sobre el uso de la memoria. |
| `encoding` | Codificación de texto (por ejemplo, `"utf-8"` para texto codificado en UTF-8). Por defecto es `"utf-8"` si es `None`. |
| `squeeze` | Si los datos analizados contienen solo una columna, devuelve una Serie. |
| `thousands` | Separador de miles (por ejemplo, `","` o `"."`); por defecto es `None`. |
| `decimal` | Separador decimal en los números (por ejemplo, `"."` o `","`); por defecto es `"."`. |
| `engine` | Motor de conversión y análisis de CSV a utilizar; puede ser uno de `"c"`, `"python"` o `"pyarrow"`. Por defecto es `"c"`, aunque el motor más nuevo `"pyarrow"` puede analizar algunos archivos mucho más rápido. El motor `"python"` es más lento pero admite algunas características que los otros motores no tienen. |

In [4]:
# para leer una pequeña cantidad de lineas
pd.options.display.max_rows = 10

In [5]:
result = pd.read_csv("examples/ex6.csv")
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [6]:
# If you want to read only a small number of rows (avoiding reading the entire file), specify that with nrows
pd.read_csv("examples/ex6.csv", nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [7]:
# To read a file in pieces, specify a chunksize as a number of rows:
chunker = pd.read_csv("examples/ex6.csv", chunksize=1000)
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [8]:
chunker = pd.read_csv("examples/ex6.csv", chunksize=1000)

tot = pd.Series([], dtype='int64')
for piece in chunker:
    tot = tot.add(piece["key"].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

In [9]:
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [10]:
data = pd.read_csv("examples/ex5.csv")
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [13]:
data.to_csv("examples/out.csv")
!type "examples/out.csv"

The system cannot find the file specified.

In [15]:
# Other delimiters can be used, of course (writing to sys.stdout so it prints the text result to the console rather than a file)
import sys
data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [18]:
# Missing values appear as empty strings in the output. You might want to denote them by some other sentinel value:
data.to_csv(sys.stdout, na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [17]:
# With no other options specified, both the row and column labels are written. Both of these can be disabled
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [19]:
# You can also write only a subset of the columns, and in an order of your choosing:
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [28]:
!type examples/ex7.csv

The syntax of the command is incorrect.

In [29]:
import csv
f = open("examples/ex7.csv")
reader = csv.reader(f)

In [30]:
for line in reader:
    print(line)
f.close()

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [31]:
with open("examples/ex7.csv") as f:
    lines = list(csv.reader(f))

In [32]:
header, values = lines[0], lines[1:]

**NOTE: Then we can create a dictionary of data columns using a dictionary comprehension and the expression zip(\*values) (beware that this will use a lot of memory on large files), which transposes rows to columns**

In [33]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

CSV files come in many different flavors. To define a new format with a different delimiter, string quoting convention, or line terminator, we could define a simple

``` [Python]
subclass of csv.Dialect:
class my_dialect(csv.Dialect):
lineterminator = "\n"
delimiter = ";"
quotechar = '"'
quoting = csv.QUOTE_MINIMAL

reader = csv.reader(f, dialect=my_dialect)
```
We could also give individual CSV dialect parameters as keywords to *csv.reader* without having to define a subclass:

`reader = csv.reader(f, delimiter="|")`

### Table 6-3. CSV dialect options

| Argument | Description |
| :--- | :--- |
| `delimiter` | Cadena de un solo carácter para separar los campos; por defecto es `","`. |
| `lineterminator` | Terminador de línea para la escritura; por defecto es `"\r\n"`. El lector ignora esto y reconoce terminadores de línea multiplataforma. |
| `quotechar` | Carácter de comillas para campos con caracteres especiales (como un delimitador); por defecto es `'"'`. |
| `quoting` | Convención de entrecomillado. Las opciones incluyen `csv.QUOTE_ALL` (entrecomillar todos los campos), `csv.QUOTE_MINIMAL` (solo campos con caracteres especiales como el delimitador), `csv.QUOTE_NONNUMERIC` y `csv.QUOTE_NONE` (sin entrecomillado). Consulta la documentación de Python para obtener todos los detalles. Por defecto es `csv.QUOTE_MINIMAL`. |
| `skipinitialspace` | Ignorar los espacios en blanco después de cada delimitador; por defecto es `False`. |
| `doublequote` | Cómo manejar el carácter de entrecomillado dentro de un campo; si es `True`, se duplica (consulta la documentación en línea para ver todos los detalles y el comportamiento). |
| `escapechar` | Cadena para escapar el delimitador si el entrecomillado está configurado en `csv.QUOTE_NONE`; desactivado por defecto. |

## JSON Data

In [35]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

There are several Python libraries for reading and writing JSON data. I’ll use json here, as it is built into the Python standard library. To convert a JSON string to Python form, use json.loads:

In [36]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [37]:
# json.dumps, on the other hand, converts a Python object back to JSON:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

How you convert a JSON object or list of objects to a DataFrame or some other data structure for analysis will be up to you. Conveniently, you can pass a list of dictionaries (which were previously JSON objects) to the DataFrame constructor and select a subset of the data fields:

In [38]:
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

    name  age
0  Scott   34
1  Katie   42

In [39]:
!type examples/example.json

The syntax of the command is incorrect.

In [40]:
# The pandas.read_json can automatically convert JSON datasets in specific arrangements into a Series or DataFrame. 
data = pd.read_json("examples/example.json")
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [41]:
# If you need to export data from pandas to JSON, one way is to use the to_json methods on Series and DataFrame
data.to_json(sys.stdout)
data.to_json(sys.stdout, orient="records")

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

## XML and HTML: Web Scraping

Python has many libraries for reading and writing data in the ubiquitous HTML and XML formats. Examples include lxml, Beautiful Soup, and html5lib. While lxml is comparatively much faster in general, the other libraries can better handle malformed HTML or XML files.

pandas has a built-in function, pandas.read_html, which uses all of these libraries to automatically parse tables out of HTML files as DataFrame objects.

In [43]:
conda install lxml beautifulsoup4 html5lib

Jupyter detected...
3 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\ferch\anaconda3\envs\pydata-book

  added / updated specs:
    - beautifulsoup4
    - html5lib
    - lxml


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautifulsoup4-4.15.0      |     pyha770c72_0          91 KB  conda-forge
    html5lib-1.1               |     pyhd8ed1ab_2          93 KB  conda-forge
    lxml-6.1.1                 |  py310h095aac5_0         1.2 MB  conda-forge
    openssl-3.6.3              |       hf411b9b_0         9.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        10.3 MB

The following NEW packages will be INSTALLED:

  html5lib           conda-forge/noarch::html5lib-1.1-pyhd8ed1ab_2
  lxml               conda-forge/win-64::lxml-6.1.1-py310h095aac5_0

The following packages will be UPDATED:

  beautifulsoup4                        4.14.3-pyha770c72_0 --> 4.15.0-pyha770c72_0
  openssl                                  3.6.2-hf411b9b_0 --> 3.6.3-hf411b9b_0



Downloading and Extracting Packages: ...working...
openssl-3.6.3        | 9.0 MB    |            |   0%

lxml-6.1.1           | 1.2 MB    |            |   0%


html5lib-1.1         | 93 KB     |            |   0%



beautifulsoup4-4.15. | 91 KB     |            |   0%


html5lib-1.1         | 93 KB     | #7         |  17%
openssl-3.6.3        | 9.0 MB    |            |   0%



beautifulsoup4-4.15. | 91 KB     | #7         |  18%


html5lib-1.1         | 93 KB     | ########## | 100%



beautifulsoup4-4.15. | 91 KB     | ########## | 100%



beautifulsoup4-4.15. | 91 KB     | ########## | 100%
openssl-3.6.3        | 9.0 MB    | 4          |   5%


html5lib-1.1         | 93 KB     | ########## | 100%


html5lib-1.1         | 93 KB     | ########## | 100%
openssl-3.6.3        | 9.0 MB    | ##5        |  26%
openssl-3.6.3        | 9.0 MB    | ########## | 100%

lxml-6.1.1           | 1.2 MB    | 1          |   1%

lxml-6.1.1           | 1.2 MB    | ###5       |  35%

lxml-6.1.1           | 1.2 MB    | ########## | 100%
openssl-3.6.3        | 9.0 MB    | ########## | 100%
openssl-3.6.3        | 9.0 MB    | ########## | 100%

lxml-6.1.1           | 1.2 MB    | ########## | 100%

lxml-6.1.1           | 1.2 MB    | ########## | 100%










                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Channel "defaults" has the following notices:
  [info] -- Tue Jun  9 00:00:00 2026
  PyTorch 2.12 with CUDA support is now available to install with your current channel (Anaconda Main). Learn more: https://anaconda.org/main/pytorch?utm_source=channel_notices


Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [46]:
# esta funcion lo que hace es obtener las tablas del html y pasarlas a un objeto dataframe, en este html solo hay una tabla
tables = pd.read_html("examples/fdic_failed_bank_list.html")
len(tables)
failures = tables[0]
failures.head()

1

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [45]:
# Pasa esta columna a datetime y agrupa los registros por año
close_timestamps = pd.to_datetime(failures["Closing Date"])
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, Length: 15, dtype: int64

## Parsing XML with lxml.objectify
Primero se mostrara el ejemplo de leer el xml con la libreria lxml.objectify y despues se mostrara utilizando pandas.read_xml.

In [47]:
# Using lxml.objectify, we parse the file and get a reference to the root node of the XML file with getroot
from lxml import objectify

path = "datasets/mta_perf/Performance_MNR.xml"
with open(path) as f:
    parsed = objectify.parse(f)
root = parsed.getroot()

*root.INDICATOR* returns a generator yielding each *<INDICATOR>* XML element. For each record, we can populate a dictionary of tag names (like *YTD_ACTUAL*) to data values (excluding a few tags) by running the following code:

In [48]:
data = []

skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
               "DESIRED_CHANGE", "DECIMAL_PLACES"]

for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

In [49]:
perf = pd.DataFrame(data)
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [50]:
# pandas.read_xml function turns this process into a one-line expression:
perf2 = pd.read_xml(path)
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

In [51]:
frame = pd.read_csv("examples/ex1.csv")
frame
frame.to_pickle("examples/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [52]:
pd.read_pickle("examples/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [49]:
!rm examples/frame_pickle

In [54]:
conda install pyarrow

Jupyter detected...
3 channel Terms of Service accepted
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\ferch\anaconda3\envs\pydata-book

  added / updated specs:
    - pyarrow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aws-c-auth-0.10.3          |       h75b6777_2         124 KB  conda-forge
    aws-c-cal-0.9.14           |       h270aff2_2          53 KB  conda-forge
    aws-c-common-0.14.0        |       hfd05255_0         235 KB  conda-forge
    aws-c-compression-0.3.2    |       h1f21522_2          23 KB  conda-forge
    aws-c-event-stream-0.7.1   |       hfbf5bbe_2          57 KB  conda-forge
    aws-c-http-0.11.0          |       h4721ae0_2         208 KB  conda-forge
    aws-c-io-0.26.3            |       h1a62f66_4         178 KB  conda-forge
    aws-c-mqtt-0.15.2          |       h10b66d2_4         207 KB  conda-forge
    aws-c-s3-0.12.5            |       h425879c_1         140 KB  conda-forge
    aws-c-sdkutils-0.2.4       |       h1f21522_6          55 KB  conda-forge
    aws-checksums-0.2.10       |       h1f21522_2         114 KB  conda-forge
    aws-crt-cpp-0.40.0         |       hcaec180_1         304 KB  conda-forge
    aws-sdk-cpp-1.11.747       |       h5d5b8b4_6        22.7 MB  conda-forge
    azure-core-cpp-1.16.2      |       h49e36cd_0         489 KB  conda-forge
    azure-identity-cpp-1.13.3  |       h5ffce34_1         415 KB  conda-forge
    azure-storage-blobs-cpp-12.17.0|       h81bf7d1_1         779 KB  conda-forge
    azure-storage-common-cpp-12.13.0|       h5ffce34_0         250 KB  conda-forge
    azure-storage-files-datalake-cpp-12.15.0|       h85968ff_0         437 KB  conda-forge
    c-ares-1.34.6              |       hfd05255_0         189 KB  conda-forge
    libabseil-20260107.1       | cxx17_h0eb2380_0         1.8 MB  conda-forge
    libarrow-24.0.0            |   hae8e908_5_cpu         4.1 MB  conda-forge
    libarrow-acero-24.0.0      |   h7d8d6a5_5_cpu         436 KB  conda-forge
    libarrow-compute-24.0.0    |   h081cd8e_5_cpu         1.7 MB  conda-forge
    libarrow-dataset-24.0.0    |   h7d8d6a5_5_cpu         418 KB  conda-forge
    libarrow-substrait-24.0.0  |   h524e9bd_5_cpu         353 KB  conda-forge
    libcrc32c-1.1.2            |       h0e60522_0          25 KB  conda-forge
    libcurl-8.20.0             |       h8206538_0         384 KB  conda-forge
    libevent-2.1.12            |       h3671451_1         401 KB  conda-forge
    libgoogle-cloud-3.5.0      |       he22669a_1          18 KB  conda-forge
    libgoogle-cloud-storage-3.5.0|       he04ea4c_1          18 KB  conda-forge
    libgrpc-1.78.1             |       h9ff2b3e_0        11.0 MB  conda-forge
    libopentelemetry-cpp-1.27.0|       hc88f397_0         3.4 MB  conda-forge
    libopentelemetry-cpp-headers-1.27.0|       h57928b3_0         425 KB  conda-forge
    libparquet-24.0.0          |   h7051d1f_5_cpu         942 KB  conda-forge
    libprotobuf-6.33.5         |       h6cf2d3c_1         6.8 MB  conda-forge
    libre2-11-2025.11.05       |       h04e5de1_1         260 KB  conda-forge
    libssh2-1.11.1             |       h9aa295b_0         286 KB  conda-forge
    libthrift-0.22.0           |       h2e43b2f_2         619 KB  conda-forge
    libutf8proc-2.11.3         |       hb980946_0          87 KB  conda-forge
    lz4-c-1.10.0               |       h2466b09_1         137 KB  conda-forge
    nlohmann_json-3.12.0       |       h5112557_1         132 KB  conda-forge
    orc-2.3.0                  |       h8fc0eb6_0         1.4 MB  conda-forge
    prometheus-cpp-1.3.0       |       hcea2f5d_0         179 KB  conda-forge
    pyarrow-24.0.0             |  py310h5588dad_0          27 KB  conda-forge
    pyarrow-core-24.0.0        |py310hc34f82c_0_cpu         3.5 MB  conda-forge
    re2-2025.11.05             |       ha104f34_1         215 KB  conda-forge
    snappy-1.2.2               |       h7fa0ca8_1          66 KB  conda-forge
    vs2015_runtime-14.51.36231 |      h84cd919_38          20 KB  conda-forge
    zlib-1.3.2                 |       hfd05255_2         830 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        66.7 MB

The following NEW packages will be INSTALLED:

  aws-c-auth         conda-forge/win-64::aws-c-auth-0.10.3-h75b6777_2
  aws-c-cal          conda-forge/win-64::aws-c-cal-0.9.14-h270aff2_2
  aws-c-common       conda-forge/win-64::aws-c-common-0.14.0-hfd05255_0
  aws-c-compression  conda-forge/win-64::aws-c-compression-0.3.2-h1f21522_2
  aws-c-event-stream conda-forge/win-64::aws-c-event-stream-0.7.1-hfbf5bbe_2
  aws-c-http         conda-forge/win-64::aws-c-http-0.11.0-h4721ae0_2
  aws-c-io           conda-forge/win-64::aws-c-io-0.26.3-h1a62f66_4
  aws-c-mqtt         conda-forge/win-64::aws-c-mqtt-0.15.2-h10b66d2_4
  aws-c-s3           conda-forge/win-64::aws-c-s3-0.12.5-h425879c_1
  aws-c-sdkutils     conda-forge/win-64::aws-c-sdkutils-0.2.4-h1f21522_6
  aws-checksums      conda-forge/win-64::aws-checksums-0.2.10-h1f21522_2
  aws-crt-cpp        conda-forge/win-64::aws-crt-cpp-0.40.0-hcaec180_1
  aws-sdk-cpp        conda-forge/win-64::aws-sdk-cpp-1.11.747-h5d5b8b4_6
  azure-core-cpp     conda-forge/win-64::azure-core-cpp-1.16.2-h49e36cd_0
  azure-identity-cpp conda-forge/win-64::azure-identity-cpp-1.13.3-h5ffce34_1
  azure-storage-blo~ conda-forge/win-64::azure-storage-blobs-cpp-12.17.0-h81bf7d1_1
  azure-storage-com~ conda-forge/win-64::azure-storage-common-cpp-12.13.0-h5ffce34_0
  azure-storage-fil~ conda-forge/win-64::azure-storage-files-datalake-cpp-12.15.0-h85968ff_0
  c-ares             conda-forge/win-64::c-ares-1.34.6-hfd05255_0
  libabseil          conda-forge/win-64::libabseil-20260107.1-cxx17_h0eb2380_0
  libarrow           conda-forge/win-64::libarrow-24.0.0-hae8e908_5_cpu
  libarrow-acero     conda-forge/win-64::libarrow-acero-24.0.0-h7d8d6a5_5_cpu
  libarrow-compute   conda-forge/win-64::libarrow-compute-24.0.0-h081cd8e_5_cpu
  libarrow-dataset   conda-forge/win-64::libarrow-dataset-24.0.0-h7d8d6a5_5_cpu
  libarrow-substrait conda-forge/win-64::libarrow-substrait-24.0.0-h524e9bd_5_cpu
  libcrc32c          conda-forge/win-64::libcrc32c-1.1.2-h0e60522_0
  libcurl            conda-forge/win-64::libcurl-8.20.0-h8206538_0
  libevent           conda-forge/win-64::libevent-2.1.12-h3671451_1
  libgoogle-cloud    conda-forge/win-64::libgoogle-cloud-3.5.0-he22669a_1
  libgoogle-cloud-s~ conda-forge/win-64::libgoogle-cloud-storage-3.5.0-he04ea4c_1
  libgrpc            conda-forge/win-64::libgrpc-1.78.1-h9ff2b3e_0
  libopentelemetry-~ conda-forge/win-64::libopentelemetry-cpp-1.27.0-hc88f397_0
  libopentelemetry-~ conda-forge/win-64::libopentelemetry-cpp-headers-1.27.0-h57928b3_0
  libparquet         conda-forge/win-64::libparquet-24.0.0-h7051d1f_5_cpu
  libprotobuf        conda-forge/win-64::libprotobuf-6.33.5-h6cf2d3c_1
  libre2-11          conda-forge/win-64::libre2-11-2025.11.05-h04e5de1_1
  libssh2            conda-forge/win-64::libssh2-1.11.1-h9aa295b_0
  libthrift          conda-forge/win-64::libthrift-0.22.0-h2e43b2f_2
  libutf8proc        conda-forge/win-64::libutf8proc-2.11.3-hb980946_0
  lz4-c              conda-forge/win-64::lz4-c-1.10.0-h2466b09_1
  nlohmann_json      conda-forge/win-64::nlohmann_json-3.12.0-h5112557_1
  orc                conda-forge/win-64::orc-2.3.0-h8fc0eb6_0
  prometheus-cpp     conda-forge/win-64::prometheus-cpp-1.3.0-hcea2f5d_0
  pyarrow            conda-forge/win-64::pyarrow-24.0.0-py310h5588dad_0
  pyarrow-core       conda-forge/win-64::pyarrow-core-24.0.0-py310hc34f82c_0_cpu
  re2                conda-forge/win-64::re2-2025.11.05-ha104f34_1
  snappy             conda-forge/win-64::snappy-1.2.2-h7fa0ca8_1
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.51.36231-h84cd919_38
  zlib               conda-forge/win-64::zlib-1.3.2-hfd05255_2



Downloading and Extracting Packages: ...working...
aws-sdk-cpp-1.11.747 | 22.7 MB   |            |   0%

libgrpc-1.78.1       | 11.0 MB   |            |   0%


libprotobuf-6.33.5   | 6.8 MB    |            |   0%



libarrow-24.0.0      | 4.1 MB    |            |   0%




pyarrow-core-24.0.0  | 3.5 MB    |            |   0%





libopentelemetry-cpp | 3.4 MB    |            |   0%






libabseil-20260107.1 | 1.8 MB    |            |   0%







libarrow-compute-24. | 1.7 MB    |            |   0%








orc-2.3.0            | 1.4 MB    |            |   0%









libparquet-24.0.0    | 942 KB    |            |   0%










zlib-1.3.2           | 830 KB    |            |   0%











azure-storage-blobs- | 779 KB    |            |   0%












libthrift-0.22.0     | 619 KB    |            |   0%













azure-core-cpp-1.16. | 489 KB    |            |   0%














azure-storage-files- | 437 KB    |            |   0%















libarrow-acero-24.0. | 436 KB    |            |   0%
















libopentelemetry-cpp | 425 KB    |            |   0%

















libarrow-dataset-24. | 418 KB    |            |   0%


















azure-identity-cpp-1 | 415 KB    |            |   0%



















 ... (more hidden) ...

libgrpc-1.78.1       | 11.0 MB   |            |   0%



libarrow-24.0.0      | 4.1 MB    |            |   0%


libprotobuf-6.33.5   | 6.8 MB    |            |   0%
aws-sdk-cpp-1.11.747 | 22.7 MB   |            |   0%



libarrow-24.0.0      | 4.1 MB    | 8          |   8%

libgrpc-1.78.1       | 11.0 MB   | 2          |   3%


libprotobuf-6.33.5   | 6.8 MB    | 4          |   4%
aws-sdk-cpp-1.11.747 | 22.7 MB   | 1          |   1%

libgrpc-1.78.1       | 11.0 MB   | 7          |   8%


libprotobuf-6.33.5   | 6.8 MB    | #1         |  11%



libarrow-24.0.0      | 4.1 MB    | ##6        |  27%
aws-sdk-cpp-1.11.747 | 22.7 MB   | 4          |   5%

libgrpc-1.78.1       | 11.0 MB   | ##5        |  25%


libprotobuf-6.33.5   | 6.8 MB    | ####1      |  41%



libarrow-24.0.0      | 4.1 MB    | ########## | 100%



libarrow-24.0.0      | 4.1 MB    | ########## | 100%




pyarrow-core-24.0.0  | 3.5 MB    |            |   0%
aws-sdk-cpp-1.11.747 | 22.7 MB   | #5         |  15%





libopentelemetry-cpp | 3.4 MB    |            |   0%

libgrpc-1.78.1       | 11.0 MB   | ####2      |  43%


libprotobuf-6.33.5   | 6.8 MB    | ######3    |  64%




pyarrow-core-24.0.0  | 3.5 MB    | 2          |   2%





libopentelemetry-cpp | 3.4 MB    | #####3     |  53%
aws-sdk-cpp-1.11.747 | 22.7 MB   | ##         |  20%

libgrpc-1.78.1       | 11.0 MB   | ######6    |  66%




pyarrow-core-24.0.0  | 3.5 MB    | #2         |  12%


libprotobuf-6.33.5   | 6.8 MB    | ########## | 100%


libprotobuf-6.33.5   | 6.8 MB    | ########## | 100%





libopentelemetry-cpp | 3.4 MB    | ########## | 100%
aws-sdk-cpp-1.11.747 | 22.7 MB   | ####6      |  47%






libabseil-20260107.1 | 1.8 MB    |            |   1%

libgrpc-1.78.1       | 11.0 MB   | ########## | 100%

libgrpc-1.78.1       | 11.0 MB   | ########## | 100%




pyarrow-core-24.0.0  | 3.5 MB    | ###5       |  35%
aws-sdk-cpp-1.11.747 | 22.7 MB   | ######7    |  68%






libabseil-20260107.1 | 1.8 MB    | ####2      |  43%







libarrow-compute-24. | 1.7 MB    |            |   1%








orc-2.3.0            | 1.4 MB    | 1          |   1%






libabseil-20260107.1 | 1.8 MB    | ########## | 100%








orc-2.3.0            | 1.4 MB    | ########## | 100%




pyarrow-core-24.0.0  | 3.5 MB    | ########6  |  86%







libarrow-compute-24. | 1.7 MB    | ########## | 100%
aws-sdk-cpp-1.11.747 | 22.7 MB   | ########3  |  83%









libparquet-24.0.0    | 942 KB    | 1          |   2%










zlib-1.3.2           | 830 KB    | 1          |   2%




pyarrow-core-24.0.0  | 3.5 MB    | ########## | 100%









libparquet-24.0.0    | 942 KB    | ########## | 100%











azure-storage-blobs- | 779 KB    | 2          |   2%










zlib-1.3.2           | 830 KB    | ########## | 100%











azure-storage-blobs- | 779 KB    | ########## | 100%













azure-core-cpp-1.16. | 489 KB    | 3          |   3%












libthrift-0.22.0     | 619 KB    | 2          |   3%














azure-storage-files- | 437 KB    | 3          |   4%













azure-core-cpp-1.16. | 489 KB    | ########## | 100%














azure-storage-files- | 437 KB    | ########## | 100%












libthrift-0.22.0     | 619 KB    | ########## | 100%















libarrow-acero-24.0. | 436 KB    | 3          |   4%















libarrow-acero-24.0. | 436 KB    | ########## | 100%
aws-sdk-cpp-1.11.747 | 22.7 MB   | ########## | 100%
aws-sdk-cpp-1.11.747 | 22.7 MB   | ########## | 100%
















libopentelemetry-cpp | 425 KB    | 3          |   4%
















libopentelemetry-cpp | 425 KB    | ########## | 100%


















azure-identity-cpp-1 | 415 KB    | 3          |   4%

















libarrow-dataset-24. | 418 KB    | 3          |   4%


















azure-identity-cpp-1 | 415 KB    | ########## | 100%

















libarrow-dataset-24. | 418 KB    | ########## | 100%



















 ... (more hidden) ...



















 ... (more hidden) ...



libarrow-24.0.0      | 4.1 MB    | ########## | 100%





libopentelemetry-cpp | 3.4 MB    | ########## | 100%





libopentelemetry-cpp | 3.4 MB    | ########## | 100%


libprotobuf-6.33.5   | 6.8 MB    | ########## | 100%








orc-2.3.0            | 1.4 MB    | ########## | 100%








orc-2.3.0            | 1.4 MB    | ########## | 100%







libarrow-compute-24. | 1.7 MB    | ########## | 100%







libarrow-compute-24. | 1.7 MB    | ########## | 100%

libgrpc-1.78.1       | 11.0 MB   | ########## | 100%






libabseil-20260107.1 | 1.8 MB    | ########## | 100%






libabseil-20260107.1 | 1.8 MB    | ########## | 100%










zlib-1.3.2           | 830 KB    | ########## | 100%










zlib-1.3.2           | 830 KB    | ########## | 100%









libparquet-24.0.0    | 942 KB    | ########## | 100%









libparquet-24.0.0    | 942 KB    | ########## | 100%











azure-storage-blobs- | 779 KB    | ########## | 100%











azure-storage-blobs- | 779 KB    | ########## | 100%














azure-storage-files- | 437 KB    | ########## | 100%














azure-storage-files- | 437 KB    | ########## | 100%













azure-core-cpp-1.16. | 489 KB    | ########## | 100%













azure-core-cpp-1.16. | 489 KB    | ########## | 100%















libarrow-acero-24.0. | 436 KB    | ########## | 100%















libarrow-acero-24.0. | 436 KB    | ########## | 100%




pyarrow-core-24.0.0  | 3.5 MB    | ########## | 100%












libthrift-0.22.0     | 619 KB    | ########## | 100%












libthrift-0.22.0     | 619 KB    | ########## | 100%


















azure-identity-cpp-1 | 415 KB    | ########## | 100%


















azure-identity-cpp-1 | 415 KB    | ########## | 100%

















libarrow-dataset-24. | 418 KB    | ########## | 100%

















libarrow-dataset-24. | 418 KB    | ########## | 100%



















 ... (more hidden) ...



















 ... (more hidden) ...
















libopentelemetry-cpp | 425 KB    | ########## | 100%
















libopentelemetry-cpp | 425 KB    | ########## | 100%
aws-sdk-cpp-1.11.747 | 22.7 MB   | ########## | 100%





















































































































































































































































































































































































































































































 done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [56]:
fec = pd.read_parquet('datasets/fec/fec.parquet')

ArrowKeyError: A type extension with name pandas.period already defined

## Reading Microsoft Excel Files

pandas also supports reading tabular data stored in Excel 2003 (and higher) files using either the pandas.ExcelFile class or pandas.read_excel function. Internally, these tools use the add-on packages xlrd and openpyxl to read old-style XLS and newer XLSX files, respectively. These must be installed separately from pandas using pip or conda:

`conda install openpyxl xlrd`

In [58]:
conda install openpyxl xlrd

Jupyter detected...
3 channel Terms of Service accepted
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\ferch\anaconda3\envs\pydata-book

  added / updated specs:
    - openpyxl

Note: you may need to restart the kernel to use updated packages.
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    et_xmlfile-2.0.0           |     pyhd8ed1ab_1          21 KB  conda-forge
    openpyxl-3.1.5             |  py310h5fa2519_3         378 KB  conda-forge
    xlrd-2.0.2                 |     pyhd8ed1ab_0          91 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         491 KB

The following NEW packages will be INSTALLED:

  et_xmlfile         conda-forge/noarch::et_xmlfile-2.0.0-pyhd8ed1ab_1
  openpyxl           conda-forge/win-64::openpyxl-3.1.5-py310h5fa2519_3
  xlrd               conda-forge/noarch::xlrd-2.0.2-pyhd8ed1ab_0



Downloading and Extracting Packages: ...working...
openpyxl-3.1.5       | 378 KB    |            |   0%

xlrd-2.0.2           | 91 KB     |            |   0%


et_xmlfile-2.0.0     | 21 KB     |            |   0%


et_xmlfile-2.0.0     | 21 KB     | #######4   |  75%


et_xmlfile-2.0.0     | 21 KB     | ########## | 100%

xlrd-2.0.2           | 91 KB     | #7         |  17%


et_xmlfile-2.0.0     | 21 KB     | ########## | 100%

xlrd-2.0.2           | 91 KB     | ########## | 100%

xlrd-2.0.2           | 91 KB     | ########## | 100%
openpyxl-3.1.5       | 378 KB    | 4          |   4%
openpyxl-3.1.5       | 378 KB    | ########## | 100%
openpyxl-3.1.5       | 378 KB    | ########## | 100%
openpyxl-3.1.5       | 378 KB    | ########## | 100%






                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [59]:
xlsx = pd.ExcelFile("examples/ex1.xlsx")

In [60]:
# This object can show you the list of available sheet names in the file
xlsx.sheet_names

['Sheet1']

In [61]:
# Data stored in a sheet can then be read into DataFrame with parse:
xlsx.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [62]:
xlsx.parse(sheet_name="Sheet1", index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

If you are reading multiple sheets in a file, then it is faster to create the pandas.Excel File, but you can also simply pass the filename to pandas.read_excel:

In [63]:
frame = pd.read_excel("examples/ex1.xlsx", sheet_name="Sheet1")
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [64]:
writer = pd.ExcelWriter("examples/ex2.xlsx")
frame.to_excel(writer, "Sheet1")
writer.close()

C:\Users\ferch\AppData\Local\Temp\ipykernel_24848\4135277578.py:2: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  frame.to_excel(writer, "Sheet1")

In [66]:
frame.to_excel("examples/ex2.xlsx")

In [67]:
!rm examples/ex2.xlsx

'rm' is not recognized as an internal or external command,
operable program or batch file.

In [68]:
!rm -f examples/mydata.h5

'rm' is not recognized as an internal or external command,
operable program or batch file.

## Using HDF5 Format
HDF5 is a respected file format intended for storing large quantities of scientific array data. It is available as a C library, and it has interfaces available in many other languages, including Java, Julia, MATLAB, and Python. The “HDF” in HDF5 stands for hierarchical data format. Each HDF5 file can store multiple datasets and supporting metadata. Compared with simpler formats, HDF5 supports on-the-fly compression with a variety of compression modes, enabling data with repeated patterns to be stored more efficiently. HDF5 can be a good choice for working with datasets that don’t fit into memory, as you can efficiently read and write small sections of much larger arrays.

In [69]:
conda install pytables

Jupyter detected...
3 channel Terms of Service accepted
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\ferch\anaconda3\envs\pydata-book

  added / updated specs:
    - pytables


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blosc-1.21.6               |       hfd34d9b_1          49 KB  conda-forge
    c-blosc2-2.15.2            |       h9e57077_1         210 KB  conda-forge
    hdf5-1.14.4                |nompi_hd5d9e70_105         2.0 MB  conda-forge
    libaec-1.1.5               |       haf901d7_0          34 KB  conda-forge
    numexpr-2.14.1             |mkl_py310hd48cd34_2         180 KB  conda-forge
    pillow-12.0.0              |  py310he90726f_1         768 KB  conda-forge
    py-cpuinfo-9.0.0           |     pyhd8ed1ab_1          25 KB  conda-forge
    pytables-3.10.1            |  py310h36d347b_4         1.2 MB  conda-forge
    zlib-ng-2.2.5              |       h32d8bfd_1         109 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.5 MB

The following NEW packages will be INSTALLED:

  blosc              conda-forge/win-64::blosc-1.21.6-hfd34d9b_1
  c-blosc2           conda-forge/win-64::c-blosc2-2.15.2-h9e57077_1
  hdf5               conda-forge/win-64::hdf5-1.14.4-nompi_hd5d9e70_105
  libaec             conda-forge/win-64::libaec-1.1.5-haf901d7_0
  numexpr            conda-forge/win-64::numexpr-2.14.1-mkl_py310hd48cd34_2
  py-cpuinfo         conda-forge/noarch::py-cpuinfo-9.0.0-pyhd8ed1ab_1
  pytables           conda-forge/win-64::pytables-3.10.1-py310h36d347b_4

The following packages will be DOWNGRADED:

  pillow                             12.2.0-py310h712baa7_0 --> 12.0.0-py310he90726f_1
  zlib-ng                                  2.3.3-h0261ad2_1 --> 2.2.5-h32d8bfd_1



Downloading and Extracting Packages: ...working...
hdf5-1.14.4          | 2.0 MB    |            |   0%

pytables-3.10.1      | 1.2 MB    |            |   0%


pillow-12.0.0        | 768 KB    |            |   0%



c-blosc2-2.15.2      | 210 KB    |            |   0%




numexpr-2.14.1       | 180 KB    |            |   0%





zlib-ng-2.2.5        | 109 KB    |            |   0%






blosc-1.21.6         | 49 KB     |            |   0%







libaec-1.1.5         | 34 KB     |            |   0%








py-cpuinfo-9.0.0     | 25 KB     |            |   0%




numexpr-2.14.1       | 180 KB    | 8          |   9%




numexpr-2.14.1       | 180 KB    | ########## | 100%




numexpr-2.14.1       | 180 KB    | ########## | 100%




numexpr-2.14.1       | 180 KB    | ########## | 100%
hdf5-1.14.4          | 2.0 MB    |            |   1%
hdf5-1.14.4          | 2.0 MB    | ##         |  21%





zlib-ng-2.2.5        | 109 KB    | #4         |  15%





zlib-ng-2.2.5        | 109 KB    | ########## | 100%


pillow-12.0.0        | 768 KB    | 2          |   2%





zlib-ng-2.2.5        | 109 KB    | ########## | 100%
hdf5-1.14.4          | 2.0 MB    | ########## | 100%






blosc-1.21.6         | 49 KB     | ###2       |  33%






blosc-1.21.6         | 49 KB     | ########## | 100%


pillow-12.0.0        | 768 KB    | #####2     |  52%



c-blosc2-2.15.2      | 210 KB    | 7          |   8%






blosc-1.21.6         | 49 KB     | ########## | 100%







libaec-1.1.5         | 34 KB     | ####7      |  48%


pillow-12.0.0        | 768 KB    | ########## | 100%







libaec-1.1.5         | 34 KB     | ########## | 100%








py-cpuinfo-9.0.0     | 25 KB     | ######3    |  64%








py-cpuinfo-9.0.0     | 25 KB     | ########## | 100%



c-blosc2-2.15.2      | 210 KB    | ########## | 100%







libaec-1.1.5         | 34 KB     | ########## | 100%








py-cpuinfo-9.0.0     | 25 KB     | ########## | 100%



c-blosc2-2.15.2      | 210 KB    | ########## | 100%



c-blosc2-2.15.2      | 210 KB    | ########## | 100%
hdf5-1.14.4          | 2.0 MB    | ########## | 100%
hdf5-1.14.4          | 2.0 MB    | ########## | 100%


pillow-12.0.0        | 768 KB    | ########## | 100%


pillow-12.0.0        | 768 KB    | ########## | 100%

pytables-3.10.1      | 1.2 MB    | 1          |   1%

pytables-3.10.1      | 1.2 MB    | ##3        |  24%

pytables-3.10.1      | 1.2 MB    | ########## | 100%

pytables-3.10.1      | 1.2 MB    | ########## | 100%

pytables-3.10.1      | 1.2 MB    | ########## | 100%













































                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [70]:
frame = pd.DataFrame({"a": np.random.standard_normal(100)})
store = pd.HDFStore("examples/mydata.h5")
store["obj1"] = frame
store["obj1_col"] = frame["a"]
store

<class 'pandas.io.pytables.HDFStore'>
File path: examples/mydata.h5

In [71]:
store["obj1"]

           a
0  -0.204708
1   0.478943
2  -0.519439
3  -0.555730
4   1.965781
..       ...
95  0.795253
96  0.118110
97 -0.748532
98  0.584970
99  0.152677

[100 rows x 1 columns]

In [72]:
store.put("obj2", frame, format="table")
store.select("obj2", where=["index >= 10 and index <= 15"])
store.close()

           a
10  1.007189
11 -1.296221
12  0.274992
13  0.228913
14  1.352917
15  0.886429

In [73]:
frame.to_hdf("examples/mydata.h5", "obj3", format="table")
pd.read_hdf("examples/mydata.h5", "obj3", where=["index < 5"])

C:\Users\ferch\AppData\Local\Temp\ipykernel_24848\2659235977.py:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_hdf except for the argument 'path_or_buf' will be keyword-only.
  frame.to_hdf("examples/mydata.h5", "obj3", format="table")

          a
0 -0.204708
1  0.478943
2 -0.519439
3 -0.555730
4  1.965781

In [74]:
import os
os.remove("examples/mydata.h5")

## 6.3 Interacting with Web APIs
Many websites have public APIs providing data feeds via JSON or some other format. There are a number of ways to access these APIs from Python; one method that I recommend is the requests package. 

To find the last 30 GitHub issues for pandas on GitHub, we can make a GET HTTP request using the add-on requests library:

In [75]:
conda install requests

Jupyter detected...
3 channel Terms of Service accepted
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [76]:
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp.raise_for_status()
resp

It’s a good practice to always call raise_for_status after using requests.get to check for HTTP errors.

The response object’s json method will return a Python object containing the parsed JSON data as a dictionary or list (depending on what JSON is returned):

In [77]:
data = resp.json()
data[0]["title"]

'TST: wrap parametrize iterables in list() for pytest 9.1+'

In [78]:
issues = pd.DataFrame(data, columns=["number", "title",
                                     "labels", "state"])
issues

,number,title,labels,state
0,65888,TST: wrap parametrize iterables in list() for pytest 9.1+,[],open
1,65885,PERF: Speed up `import pandas` with PEP 810 lazy imports,[],open
2,65881,DEPR: Series.dt.freq returning a string instead of DateOffset,"[{'id': 53181044, 'node_id': 'MDU6TGFiZWw1MzE4MTA0NA==', 'url': 'https:...",open
3,65878,BUG: Validate var_name doesn't collide with id_vars or value_name in melt,[],open
4,65877,DEPR: deprecate DataFrame construction from ragged list of sequences,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4NTE1Mg==', 'url': 'https:...",open
...,...,...,...,...
25,65837,PERF: Big slowdown of searchsorted on pd.Series,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api...",open
26,65836,BUG: Series.sort_values ignore_index has no effect on already sorted Se...,[],open
27,65835,BUG: Fix nanany/nanall raising ValueError with skipna=False on nullable...,[],open
28,65833,BUG: ignore_index=True has no effect on already sorted Series,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
29,65832,BUG: respect check_series_type=False for ndarray subclass-backed Series...,[],open

## 6.4 Interacting with Databases
In a business setting, a lot of data may not be stored in text or Excel files. SQL-based relational databases (such as SQL Server, PostgreSQL, and MySQL) are in wide use, and many alternative databases have become quite popular. The choice of database is usually dependent on the performance, data integrity, and scalability needs of an application.

pandas has some functions to simplify loading the results of a SQL query into a DataFrame. As an example, I’ll create a SQLite3 database using Python’s built-in sqlite3 driver:

In [79]:
import sqlite3

query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""

con = sqlite3.connect("mydata.sqlite")
con.execute(query)
con.commit()

In [80]:
data = [("Atlanta", "Georgia", 1.25, 6),
        ("Tallahassee", "Florida", 2.6, 3),
        ("Sacramento", "California", 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

con.executemany(stmt, data)
con.commit()

In [81]:
# Most Python SQL drivers return a list of tuples when selecting data from a table:
cursor = con.execute("SELECT * FROM test")
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

You can pass the list of tuples to the DataFrame constructor, but you also need the column names, contained in the cursor’s description attribute. Note that for SQLite3, the cursor description only provides column names (the other fields, which are part of Python’s Database API specification, are None), but for some other database drivers, more column information is provided:

In [82]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [83]:
conda install sqlalchemy

Jupyter detected...
3 channel Terms of Service accepted
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\ferch\anaconda3\envs\pydata-book

  added / updated specs:
    - sqlalchemy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    greenlet-3.5.1             |  py310h699e580_0         215 KB  conda-forge
    sqlalchemy-2.0.51          |  py310h1637853_0         2.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following NEW packages will be INSTALLED:

  greenlet           conda-forge/win-64::greenlet-3.5.1-py310h699e580_0
  sqlalchemy         conda-forge/win-64::sqlalchemy-2.0.51-py310h1637853_0



Downloading and Extracting Packages: ...working...
sqlalchemy-2.0.51    | 2.8 MB    |            |   0%

greenlet-3.5.1       | 215 KB    |            |   0%
sqlalchemy-2.0.51    | 2.8 MB    |            |   1%
sqlalchemy-2.0.51    | 2.8 MB    | 6          |   7%

greenlet-3.5.1       | 215 KB    | 7          |   7%
sqlalchemy-2.0.51    | 2.8 MB    | #1         |  11%

greenlet-3.5.1       | 215 KB    | ########## | 100%
sqlalchemy-2.0.51    | 2.8 MB    | #5         |  16%

greenlet-3.5.1       | 215 KB    | ########## | 100%

greenlet-3.5.1       | 215 KB    | ########## | 100%
sqlalchemy-2.0.51    | 2.8 MB    | ###3       |  34%
sqlalchemy-2.0.51    | 2.8 MB    | ####9      |  49%
sqlalchemy-2.0.51    | 2.8 MB    | ########   |  81%
sqlalchemy-2.0.51    | 2.8 MB    | ########## | 100%
sqlalchemy-2.0.51    | 2.8 MB    | ########## | 100%
sqlalchemy-2.0.51    | 2.8 MB    | ########## | 100%



                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [84]:
import sqlalchemy as sqla
db = sqla.create_engine("sqlite:///mydata.sqlite")
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [88]:
!rm mydata.sqlite

'rm' is not recognized as an internal or external command,
operable program or batch file.